linters:
  enable:
    - goimports
    - golint
    - govet
    - deadcode
    - gosimple
    - errcheck
    - ineffassign
    - staticcheck
    - goconst
    - dupl
    - exhaustive
    - gocognit
    - godot
    - goconst
    - godox
    - goerr113
    - importas
    - nilerr
    - prealloc
